---
# roles/common/tasks/main.yml
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required system packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
      - software-properties-common
    state: present

- name: Create directory for application
  file:
    path: /opt/devops-project
    state: directory
    mode: '0755'

- name: Ensure Docker network configuration directory exists
  file:
    path: /opt/devops-project/networks
    state: directory
    mode: '0755'